# Generated by Django 5.2 on 2025-04-03 22:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='Admin username', max_length=150, unique=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Can log into admin site')),
                ('is_superuser', models.BooleanField(default=False, help_text='Has all permissions')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='When the admin was created')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this admin belongs to', related_name='admin_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this admin', related_name='admin_users', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
