# Generated by Django 5.2 on 2025-04-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_balance_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emotes',
            field=models.TextField(default='{}', help_text="JSON of emote counts, e.g., {'pity1': 1, 'common1': 3}"),
        ),
    ]
