# Generated by Django 5.2 on 2025-04-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_emotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_artist',
            field=models.BooleanField(default=False, help_text='User is an Artist, gets all artist emotes'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_developer',
            field=models.BooleanField(default=False, help_text='User is a Developer, gets all developer emotes'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_founder',
            field=models.BooleanField(default=False, help_text='User is a Founder, gets all founder emotes'),
        ),
    ]
