# Generated by Django 5.1.7 on 2025-03-20 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmoteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.FileField(upload_to='emotes/')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary'), ('mythic', 'Mythic')], max_length=20)),
                ('animated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Emote Type',
                'verbose_name_plural': 'Emote Types',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emotes',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.CreateModel(
            name='UserEmote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.donation')),
                ('emote_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emotetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Emote',
                'verbose_name_plural': 'User Emotes',
            },
        ),
        migrations.DeleteModel(
            name='Emote',
        ),
    ]
