# Generated by Django 5.1.7 on 2025-03-20 23:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emotetype_remove_profile_emotes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useremote',
            unique_together={('user', 'emote_type')},
        ),
        migrations.AddField(
            model_name='emotetype',
            name='available_instances',
            field=models.PositiveIntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='useremote',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='useremote',
            name='donation',
        ),
    ]
