# Generated by Django 5.1.7 on 2025-03-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_useremote_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotetype',
            name='available_instances',
            field=models.PositiveIntegerField(),
        ),
    ]
