# Generated by Django 5.2 on 2025-04-06 02:25

import django.core.validators
import emotes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Upload a square PNG or GIF (supports transparency and animation).', null=True, upload_to='emotes/', validators=[emotes.models.validate_square_image])),
                ('rarity', models.CharField(choices=[('pity', 'Pity'), ('earlydays', 'EarlyDays'), ('developer', 'Developer'), ('artist', 'Artist'), ('founder', 'Founder'), ('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary'), ('exotic', 'Exotic'), ('mythic', 'Mythic'), ('novelty', 'Novelty')], default='common', max_length=20)),
                ('roll_chance', models.FloatField(default=0.0, help_text='Chance of rolling this emote (0-100%), 0 for special emotes', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('max_instances', models.BigIntegerField(default=0, help_text='Max instances allowed (0 for unlimited/special)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
