# Generated by Django 5.2 on 2025-04-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emote',
            name='chat_display_name',
            field=models.CharField(default='ER:temp', editable=False, help_text="Unique emote name with 'ER:' (e.g., ER:pity1)", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='emote',
            name='name',
            field=models.CharField(help_text="User-friendly name without 'ER:' prefix (e.g., pity1)", max_length=47),
        ),
    ]
