# Generated by Django 5.2 on 2025-04-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotes', '0002_emote_chat_display_name_alter_emote_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emote',
            name='max_instances',
        ),
        migrations.RemoveField(
            model_name='emote',
            name='roll_chance',
        ),
        migrations.AlterField(
            model_name='emote',
            name='chat_display_name',
            field=models.CharField(editable=False, help_text="Unique emote name with 'ER:' (e.g., ER:emote)", max_length=50, unique=True),
        ),
    ]
